dirs = {'/Volumes/Data/song/lr12/all', ...
    '/Volumes/Data/song/lr13/all', ...
    '/Volumes/Data/song/lr28/all', ...
    '/Volumes/Data/song/lr77/all', ...
    '/Volumes/Data/song/lny42', ...
    '/Volumes/Data/song/lny46', ...
    '/Volumes/Data/song/lny4rb'}


for i = 1:length(dirs)
    try
        cd(dirs{i});
        learn_detector('log_file_exists_action', 'append');
    catch ME
        warning('Caught error:');
        ME
    end
end
